### ISSUE TITLE
X!Tandem header translations are missing

### ISSUE THREAD

**Issue by MKoesters** [uparma/uparma-lib#18]
Seems like they never were there, at least I cant find them in ursgal.
Is there any special reason they are not here or should we add them?

**Comment by StSchulze** [comment]
The historical reason (as far as I know) why they aren't there is that the output of xtandem isn't a csv, i.e. there are no headers to translate, and the output of the xtandem2csv engine already has the correct headers. But of course that's not a very logical argument, since there's still a translation, just in xtandem2csv.

Long story short: I think it should be added, yes.

**Comment by ArtiVlasov** [comment]
Merged & closed ;)
